
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.util.Renderable": "../../../platform/src/util/Renderable.js",
  "Ext.util.Bindable": "../../../platform/src/util/Bindable.js",
  "Ext.state": "../../../platform/src/state",
  "Ext.layout.component.Auto": "../../../platform/src/layout/component/Auto.js",
  "Ext.util.HashMap": "../../../platform/src/util/HashMap.js",
  "Ext.container.AbstractContainer": "../../../platform/src/container/AbstractContainer.js",
  "Ext.ComponentLoader": "../../../platform/src/ComponentLoader.js",
  "Ext.util.Queue": "../../../platform/src/util/Queue.js",
  "Ext": "../../src",
  "Ext.chart": "../../../platform/src/chart",
  "Ext.layout.ClassList": "../../../platform/src/layout/ClassList.js",
  "Ext.ux": "extjs/ux"
});
Ext.ClassManager.addNameAlternateMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Huskar.view.Header": [],
  "Huskar.view.Navigation": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Huskar.store.Restaurants": [],
  "Huskar.store.Files": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "ExtThemeNeptune.panel.Table": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [],
  "Huskar.controller.Main": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "ExtThemeNeptune.picker.Month": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "Huskar.model.dd.Simple": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Huskar.view.tab.FramedTabs": [],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Huskar.view.dataview.MultiSortButton": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.FieldReplicator": [],
  "Huskar.view.dd.GridToForm": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "ExtThemeNeptune.panel.Panel": [],
  "Huskar.view.form.Number": [],
  "Huskar.view.tree.TwoTrees": [],
  "Huskar.view.toolbar.BasicToolbar": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Huskar.view.grid.LockingGrid": [],
  "Huskar.view.tree.Reorder": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "Huskar.view.dd.FieldToGrid": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Huskar.view.MainTabPanel": [],
  "Huskar.model.grid.Employee": [],
  "Ext.ux.GMapPanel": [],
  "Huskar.view.grid.SlidingPager": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Huskar.model.grid.Office": [],
  "Ext.ux.layout.Center": [],
  "Huskar.view.Viewport": [],
  "Huskar.model.tree.Task": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "Huskar.view.tab.IconTabs": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Huskar.view.tree.XmlTree": [],
  "Huskar.view.button.LeftTextButtons": [],
  "Huskar.model.grid.Plant": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "Huskar.view.slider.SliderField": [],
  "Huskar.view.button.MenuBottomButtons": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Huskar.store.States": [],
  "Ext.ux.RowExpander": [],
  "Huskar.data.DataSets": [],
  "Ext.ux.event.Player": [],
  "Huskar.model.State": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Huskar.view.dataview.MultiSort": [],
  "Huskar.view.form.Checkout": [],
  "Huskar.view.layout.Accordion": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Huskar.view.grid.ProgressBarPager": [],
  "Huskar.view.form.FormGrid": [],
  "Huskar.view.grid.ArrayGrid": [],
  "Huskar.view.button.MenuButtons": [],
  "Huskar.view.grid.MultipleSorting": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Huskar.DummyText": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Huskar.view.grid.CellEditing": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Huskar.view.tab.PlainTabs": [],
  "Huskar.model.Company": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [],
  "ExtThemeNeptune.Component": [],
  "Huskar.view.form.RegisterForm": [],
  "Huskar.model.Restaurant": []
});
Ext.ClassManager.addNameAliasMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Huskar.view.Header": [
    "widget.appHeader"
  ],
  "Huskar.view.panel.UserPanel": [],
  "Huskar.view.panel.RolePanel": [],
  
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Huskar.store.Restaurants": [],
  "Huskar.store.Files": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Huskar.view.Navigation": [
    "widget.navigation"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "ExtThemeNeptune.panel.Table": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Huskar.controller.Main": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "ExtThemeNeptune.picker.Month": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "ExtThemeNeptune.panel.Panel": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Huskar.view.Viewport": [],
  "Huskar.model.tree.Task": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "ExtThemeNeptune.Component": [],
});
